name : Code

on:
  push:

jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - name: Print the Message
        run: echo"Code Cloned"
