name: Deploy

on:  #trigger
  workflow_call:  #whenever this workflow needs to be called from another workflow
  # push: (when the code is pushed on github, the workflow automatically runs)
  # workflow_dispatch: (whenever you want the workflow to be called manually)
  # schedule: (whenever you want the workflow to be called at a specific time)

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: clone the code
        uses: actions/checkout@v7

      - name: Deploy via nginx
        run: cp index.html /var/www/html
        
      - name: Deploy the code
        run: echo "Code deployed on AWS EC2 instance"
